In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dff = pd.read_csv("/content/drive/MyDrive/COLLAB/Modi_Tweets.csv" , encoding = "ISO-8859-1")
dff.head()

clean_text  category
0  when modi promised “minimum government maxim...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [ ]:
# prompt: create a sample of random 10000 rows only

df = dff.sample(n=10000, random_state=1)
df.shape

(10000, 2)

# **XG BOOST**

---



In [ ]:
# prompt: drop the rows where null values is predff.isnull().sum()
dff = dff.dropna()

dff.isnull().sum()

clean_text    0
category      0
dtype: int64

In [ ]:
y_train = y_train.dropna()
print(y_train.isnull().sum())
print(X_train.isnull().sum())
print(y_train.dtype)
#y_train = y_train.astype('int')

y_train = y_train.astype('int')
print(y_train.dtype)

0
0
float64
int64


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import xgboost as xgb
from sklearn.metrics import accuracy_score

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
dff['category'] = dff['category'].map(label_mapping)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(dff['clean_text'], dff['category'],
                                                    test_size=0.2, random_state=42)

# Create TF-IDF vectors from the text data
tfidf_vectorizer = TfidfVectorizer(max_features=10000)  # Adjust max_features as needed
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Create an XGBoost classifier
xgb_classifier = xgb.XGBClassifier(objective='multi:softmax', num_class=3)  # For multi-class classification

# Train the classifier
xgb_classifier.fit(X_train_tfidf, y_train)

# Predict the labels for the test data
y_pred = xgb_classifier.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [nan]

In [ ]:
# prompt: print(y_train.dtype) convert into integer datatype

y_train = y_train.astype('int')


In [ ]:

y_train = y_train.dropna()
print(y_train.isnull().sum())
print(X_train.isnull().sum())
print(y_train.dtype)
#y_train = y_train.astype('int')

y_train = y_train.astype('int')
print(y_train.dtype)

0
0
float64
int64


In [ ]:
# prompt: print classification report of above xg boost

from sklearn.metrics import classification_report

# Get the predicted labels for the test data
y_pred = xgb_classifier.predict(X_test_tfidf)

# Print the classification report-
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.83      0.59      0.69       429
           1       0.74      0.96      0.84       655
           2       0.89      0.82      0.85       916

    accuracy                           0.82      2000
   macro avg       0.82      0.79      0.79      2000
weighted avg       0.83      0.82      0.81      2000



In [ ]:
# prompt: perform bagging and boosting

from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier
import xgboost as xgb
# Bagging
bagging_classifier = BaggingClassifier(base_estimator=xgb_classifier, n_estimators=10, random_state=42)
bagging_classifier.fit(X_train_tfidf, y_train)
y_pred_bagging = bagging_classifier.predict(X_test_tfidf)
accuracy_bagging = accuracy_score(y_test, y_pred_bagging)
print("Bagging Accuracy:", accuracy_bagging)

# Boosting
boosting_classifier = AdaBoostClassifier(base_estimator=xgb_classifier, n_estimators=10, random_state=42)
boosting_classifier.fit(X_train_tfidf, y_train)
y_pred_boosting = boosting_classifier.predict(X_test_tfidf)
accuracy_boosting = accuracy_score(y_test, y_pred_boosting)
print("Boosting Accuracy:", accuracy_boosting)


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Bagging Accuracy: 0.565


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Boosting Accuracy: 0.18


In [ ]:
# prompt: split dataset df into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, df['category'], test_size=0.2, random_state=42)


# **SVM**

---



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Assuming df is your DataFrame containing the clean_text and category columns

# Drop rows with missing values in the 'clean_text' column
df.dropna(subset=['clean_text'], inplace=True)

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)

# Drop rows with NaN values in the 'category' column
df.dropna(subset=['category'], inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['category'], test_size=0.2, random_state=42)

# Create TF-IDF vectors from the text data
tfidf_vectorizer = TfidfVectorizer(max_features=3000)  # Reduce max_features for performance
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Initialize SVM classifier with optimized parameters
svm_classifier = SVC(kernel='linear', C=0.1)  # Adjust C parameter for better performance

# Train the classifier
svm_classifier.fit(X_train_tfidf, y_train)

# Predict the labels for the test data
y_pred = svm_classifier.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification report
print(classification_report(y_test, y_pred))


Accuracy: 0.48
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        36
           1       0.00      0.00      0.00        68
           2       0.48      1.00      0.65        96

    accuracy                           0.48       200
   macro avg       0.16      0.33      0.22       200
weighted avg       0.23      0.48      0.31       200



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

# Assuming df is your DataFrame containing the clean_text and category columns

# Drop rows with missing values in the 'clean_text' column
df.dropna(subset=['clean_text'], inplace=True)

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)

# Drop rows with NaN values in the 'category' column
df.dropna(subset=['category'], inplace=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['category'], test_size=0.2, random_state=42)

# Create TF-IDF vectors from the text data
tfidf_vectorizer = TfidfVectorizer(max_features=3000)  # Adjust max_features as needed
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Initialize Gradient Boosting classifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
gb_classifier.fit(X_train_tfidf, y_train)

# Predict the labels for the test data
y_pred = gb_classifier.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification report
print(classification_report(y_test, y_pred))


ValueError: y contains 1 class after sample_weight trimmed classes with zero weights, while a minimum of 2 classes are required.

In [ ]:
import pandas as pd

# Load your dataset # Replace 'your_dataset.csv' with the path to your dataset file

# Drop rows with missing values in the 'cleantext' column
dff.dropna(subset=['clean_text'], inplace=True)

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
dff['category'] = dff['category'].map(label_mapping)

# Fill NaN values in the 'category' column with a placeholder value (-999)
dff['category'].fillna(-999, inplace=True)

# Filter out rows with the placeholder value in the 'category' column
dff = dff[dff['category'] != -999]

# Check the number of samples after preprocessing
print("Number of samples after preprocessing:", len(dff))

# Now proceed with splitting the data into training and testing sets, and further processing


Number of samples after preprocessing: 162969


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
import xgboost as xgb
import numpy as np

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['category'], test_size=0.2, random_state=42)

# Create TF-IDF vectors from the text data
tfidf_vectorizer = TfidfVectorizer(max_features=5000)  # Reduce max_features to speed up computation
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Define the parameter distributions for RandomizedSearchCV
param_dist = {
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5],
    'subsample': np.arange(0.6, 1.1, 0.2),
    'colsample_bytree': np.arange(0.6, 1.1, 0.2),
    'eta': [0.01, 0.1, 0.3],
}

# Initialize XGBoost classifier
xgb_classifier = xgb.XGBClassifier(objective='multi:softmax', num_class=3)

# Perform RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=xgb_classifier, param_distributions=param_dist, n_iter=50, cv=3, scoring='accuracy', n_jobs=-1, random_state=42)
random_result = random_search.fit(X_train_tfidf, y_train)

# Get the best parameters and best accuracy
best_params = random_result.best_params_
best_accuracy = random_result.best_score_

print("Best Parameters:", best_params)
print("Best Accuracy:", best_accuracy)

# Train the XGBoost classifier with the best parameters
best_xgb_classifier = xgb.XGBClassifier(objective='multi:softmax', num_class=3, **best_params)
best_xgb_classifier.fit(X_train_tfidf, y_train)

# Predict the labels for the test data
y_pred = best_xgb_classifier.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


In [ ]:
unique_labels = y_train.unique()
print(unique_labels)

[ 1. nan  2.]


In [ ]:
# Assuming df is your DataFrame containing the clean_text and category columns

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)

# Check for out-of-range values
unique_labels = df['category'].unique()
if any(label < 0 or label >= 3 for label in unique_labels):
    raise ValueError("Invalid label values detected in 'category' column.")

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['category'], test_size=0.2, random_state=42)

# ... (remaining code)

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SpatialDropout1D
from sklearn.model_selection import train_test_split

# Assuming df is your DataFrame containing the clean_text and category columns

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['category'], test_size=0.2, random_state=42)

# Tokenize the text data
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(X_train)

# Convert text data to sequences
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

# Pad sequences to ensure uniform length
max_length = 100  # adjust as needed
X_train_padded = pad_sequences(X_train_seq, maxlen=max_length, padding='post')
X_test_padded = pad_sequences(X_test_seq, maxlen=max_length, padding='post')

# Define the LSTM model
embedding_dim = 100  # adjust as needed
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=embedding_dim, input_length=max_length))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train_padded, y_train, epochs=5, batch_size=64, validation_data=(X_test_padded, y_test))

# Evaluate the model
loss, accuracy = model.evaluate(X_test_padded, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)


In [ ]:
# prompt: RNN model for df dataset

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# Create a tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['clean_text'])

# Create sequences
sequences = tokenizer.texts_to_sequences(df['clean_text'])
padded_sequences = pad_sequences(sequences, maxlen=100)

# Create the RNN model
model = Sequential()
model.add(Embedding(len(tokenizer.word_index) + 1, 128, input_length=100))
model.add(SimpleRNN(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(padded_sequences, df['category'], epochs=10, batch_size=32)



ValueError: Expected input data to be non-empty.

In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(padded_sequences, df['category'])
print('Loss:', loss)
print('Accuracy:', accuracy)


313/313 [==============================] - 4s 11ms/step - loss: nan - accuracy: 0.3376
Loss: nan
Accuracy: 0.3375999927520752


# **VECTORIZATION**

In [ ]:
# Perform count vectorisation

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['clean_text'])

print(X.toarray())
print()
print(X.shape)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

(1000, 5211)


In [ ]:
# create a dataframe containing X

import pandas as pd
df_X = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df_X


100  1000  10000rs  1000s  100cr  104  10jp  10min  10th  10times  ...  \
0      0     0        0      0      0    0     0      0     0        0  ...   
1      0     0        0      0      0    0     0      0     0        0  ...   
2      0     0        0      0      0    0     0      0     0        0  ...   
3      0     0        0      0      0    0     0      0     0        0  ...   
4      0     0        0      0      0    0     0      0     0        0  ...   
..   ...   ...      ...    ...    ...  ...   ...    ...   ...      ...  ...   
995    0     0        0      0      0    0     0      0     0        0  ...   
996    0     0        0      0      0    0     0      0     0        0  ...   
997    0     0        0      0      0    0     0      0     0        0  ...   
998    0     0        0      0      0    0     0      0     0        0  ...   
999    0     0        0      0      0    0     0      0     0        0  ...   

     yrs  zeal  zero  ¹2000  ¼à  ¾à  ಠ ಾ  ಾೠ à³  
0      0     0     0      0   0   0   0    0      0   0  
1      1     0     0      0   0   0   0    0      0   0  
2      0     0     0      0   0   0   0    0      0   0  
3      0     0     0      0   0   0   0    0      0   0  
4      0     0     0      0   0   0   0    0      0   0  
..   ...   ...   ...    ...  ..  ..  ..  ...    ...  ..  
995    0     0     0      0   0   0   0    0      0   0  
996    0     0     0      0   0   0   0    0      0   0  
997    0     0     0      0   0   0   0    0      0   0  
998    0     0     0      0   0   0   0    0      0   0  
999    0     0     0      0   0   0   0    0      0   0  

[1000 rows x 5211 columns]

In [ ]:
# perform tf-idf on dataset

from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit and transform the data
X = vectorizer.fit_transform(df['clean_text'])

# Convert the sparse matrix to a dense array
X = X.toarray()

# Print the shape of the transformed data
print(X.shape)

(1000, 5211)


In [ ]:
bvc = pd.read_csv("df_X.csv")
bvc.iloc[:, 2000:2051]

gangs  ganja  gap  gareebi  garibi  garment  garner  gas  gather  gautam  \
0        0      0    0        0       0        0       0    0       0       0   
1        0      0    0        0       0        0       0    0       0       0   
2        0      0    0        0       0        0       0    0       0       0   
3        0      0    0        0       0        0       0    0       0       0   
4        0      0    0        0       0        0       0    0       0       0   
..     ...    ...  ...      ...     ...      ...     ...  ...     ...     ...   
995      0      0    0        0       0        0       0    0       0       0   
996      0      0    0        0       0        0       0    0       0       0   
997      0      0    0        0       0        0       0    0       0       0   
998      0      0    0        0       0        0       0    0       0       0   
999      0      0    0        0       0        0       0    0       0       0   

     ...  glimpses  global  glory  glue  goa  goal  god  godfather  godi  \
0    ...         0       0      0     0    0     0    0          0     0   
1    ...         0       0      0     0    0     0    0          0     0   
2    ...         0       0      0     0    0     0    0          0     0   
3    ...         0       0      0     0    0     0    0          0     0   
4    ...         0       0      0     0    0     0    0          0     0   
..   ...       ...     ...    ...   ...  ...   ...  ...        ...   ...   
995  ...         0       0      0     0    0     0    0          0     0   
996  ...         0       0      0     0    0     0    0          0     0   
997  ...         0       0      0     0    0     0    0          0     0   
998  ...         0       0      0     0    0     0    0          0     0   
999  ...         0       0      0     0    0     0    0          0     0   

     godly  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
995      0  
996      0  
997      0  
998      0  
999      0  

[1000 rows x 51 columns]

In [ ]:
#combining tf-idf and  count vectorization

import numpy as np
# Concatenate the TF-IDF and Bag of Words vectors
X_combined = np.concatenate((X, df_X), axis=1)

# Print the shape of the combined vector
print(X_combined.shape)
X_combined

(1000, 10422)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#create a data frame of X_combined which is a numpy.ndarray
import pandas as pd

# Convert the NumPy array to a Pandas DataFrame
df_combined = pd.DataFrame(X_combined)

# Print the DataFrame
df_combined

0      1      2      3      4      5      6      7      8      9      \
0      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
995    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
996    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
997    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
998    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
999    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

     ...  10412  10413  10414  10415  10416  10417  10418  10419  10420  10421  
0    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
995  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
996  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
997  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
998  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
999  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[1000 rows x 10422 columns]

In [ ]:
df_combined.iloc[:, 3500:3550]

3500  3501  3502  3503  3504  3505  3506  3507  3508  3509  ...  3540  \
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
995   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
996   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
997   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
998   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
999   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     3541  3542  3543  3544  3545  3546  3547  3548  3549  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
995   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
996   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
997   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
998   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
999   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[1000 rows x 50 columns]

In [ ]:
x = df_combined
print("X SHAPE : ",x.shape)
x

X SHAPE :  (10000, 41318)


0      1      2      3      4      5      6      7      8      9      \
0       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9995    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9996    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9997    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9998    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9999    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  41308  41309  41310  41311  41312  41313  41314  41315  41316  \
0     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9995  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9996  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9997  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9998  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9999  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      41317  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
9995    0.0  
9996    0.0  
9997    0.0  
9998    0.0  
9999    0.0  

[10000 rows x 41318 columns]

In [ ]:
y = df['category']
print("Y SHAPE : ",y.shape[0])
print()
y

Y SHAPE :  10000



102593    1.0
148753    1.0
2704      0.0
138001    0.0
73506     1.0
         ... 
27748     1.0
107598   -1.0
151666    0.0
77114     1.0
62391     1.0
Name: category, Length: 10000, dtype: float64

In [ ]:

X_train , X_test , y_train , y_test = train_test_split(x,y,test_size = 0.2)

NameError: name 'x' is not defined

In [ ]:
!pip install textblob

In [ ]:
from textblob import TextBlob

In [ ]:
def preprocess_text(text):
    if isinstance(text, pd.Series):
        return text.apply(lambda x: TextBlob(x).lower())
    else:
        return TextBlob(text).lower()

X_train["clean_text"] = X_train["clean_text"].apply(preprocess_text)
X_test["clean_text"] = X_test["clean_text"].apply(preprocess_text)

# **RANDOM FOREST**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Assuming df is your DataFrame containing the clean_text and category columns

# Drop rows with missing values in both 'clean_text' and 'category' columns
df.dropna(subset=['clean_text', 'category'], inplace=True)

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)



# Check if there are samples left after splitting
if len(X_train) == 0 or len(X_test) == 0:
    print("Error: No samples available for training/testing after preprocessing.")
else:
    # Create TF-IDF vectors from the text data
    tfidf_vectorizer = TfidfVectorizer(max_features=10000)  # Adjust max_features as needed
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
    X_test_tfidf = tfidf_vectorizer.transform(X_test)

    # Create a Random Forest classifier
    rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

    # Train the classifier
    rf_classifier.fit(X_train_tfidf, y_train)

    # Predict the labels for the test data
    y_pred = rf_classifier.predict(X_test_tfidf)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)


ValueError: Input y contains NaN.

In [ ]:
# prompt: create a random forest model

# Assuming df is your DataFrame containing the clean_text and category columns

# Drop rows with missing values in both 'clean_text' and 'category' columns
df.dropna(subset=['clean_text', 'category'], inplace=True)

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)

# Check if there are samples left after splitting
if len(X_train) == 0 or len(X_test) == 0:
    print("Error: No samples available for training/testing after preprocessing.")
else:
    # Create TF-IDF vectors from the text data
    tfidf_vectorizer = TfidfVectorizer(max_features=10000)  # Adjust max_features as needed
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
    X_test_tfidf = tfidf_vectorizer.transform(X_test)

    # Create a Random Forest classifier
    rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

    # Train the classifier
    rf_classifier.fit(X_train_tfidf, y_train)

    # Predict the labels for the test data
    y_pred = rf_classifier.predict(X_test_tfidf)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)


ValueError: Input y contains NaN.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Assuming df is your DataFrame containing the clean_text and category columns

# Drop rows with missing values in both 'clean_text' and 'category' columns
df.dropna(subset=['clean_text', 'category'], inplace=True)

# Map the category labels to integers starting from 0
label_mapping = {-1: 0, 0: 1, 1: 2}
df['category'] = df['category'].map(label_mapping)


# Create TF-IDF vectors from the text data
tfidf_vectorizer = TfidfVectorizer(max_features=10000)  # Adjust max_features as needed
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Create a Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=500, max_depth=50, min_samples_split=5, random_state=42)  # Example hyperparameters

# Train the classifier
rf_classifier.fit(X_train_tfidf, y_train)

# Predict the labels for the test data
y_pred = rf_classifier.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


ValueError: Input y contains NaN.

In [ ]:
def solution(numbers, pattern):
    count = 0
    for l in range(len(pattern)-1):
        print(numbers[0:3])
        if pattern[l] in numbers[0:3]:
            count += 1

    for i in numbers:
        if i < ((len(numbers))-2):
            sub_arr = numbers[i:i+3]
            print(sub_arr)
            for j in range(len(pattern)-1):
                if pattern[j] in sub_arr:
                    count += 1
    print(count)
n=list(map(int,input().split()))
p=list(map(int,input().split()))
solution(n,p)

1 2 3 4 5 6 7 
5 8 9
[1, 2, 3]
[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]
[5, 6, 7]
3


In [ ]:
def sol(numbers):
  count = 0
  for i in range(len(numbers)-1):
    if len(numbers[i])%2 == 0:
      count +=1
  return count
n=list(input().split())
sol(n)

11111 11 1111 678 56 7890


3

In [ ]:
11111 11 1111 678 56 7890

In [ ]:

def longestMonotonicSubarray(num):
  const_len = 1
  inc_len = 1
  dec_len =1
  for i in range(len(nums)-1):
    if num[i] > num[i+1]:
      inc_len += 1
      dec_len = 1
    elif num[i] < num[i+1]:
      inc_len = 1
      dec_len += 1
    else:
      inc_len += 1
      dec_len = 1
    return max(const_len,inc_len,dec_len)

num =

NameError: name 'List' is not defined

In [ ]:
for i in range(1,3):
  print(i)

1
2


In [ ]:
a = 6
b = 9
c = 5
max(a,b,c)

9

In [ ]:
def longestMonotonicSubarray(num):
        const_len = 1
        inc_len = 1
        dec_len =1

        for i in range(1,len(num)):
            if num[i] < num[i-1]:
                inc_len = 1       #2+1
                dec_len += 1
            elif num[i] > num[i-1]:
                inc_len += 1
                dec_len = 1
            else:
                inc_len = 1
                dec_len = 1
        return max(const_len,inc_len,dec_len)
num = [3,2,1]
longestMonotonicSubarray(num)

2
3


3